Update composer.json
laminas-api-tools/api-tools-skeleton pull request #48
Opened 2022-02-07 21:23 UTC by gildonei

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Fixed _post-create-project-cmd_ for windows by replacing single quotes for double quotes

Testing in Win 11 / php 7.4.9 cli using git clone / composer install

2022-02-07 21:24 UTC, Ocramius requested changes

2022-02-07 21:24 UTC, Ocramius commented on composer.json
> +            "php -r \"if (file_exists(\"CHANGELOG.md\")) unlink(\"CHANGELOG.md\");\""
Let's use single quotes around the wrapped strings here - the escaping you provided is incomplete as-is :)

2022-02-07 21:29 UTC, gildonei commented on composer.json
> +            "php -r \"if (file_exists(\"CHANGELOG.md\")) unlink(\"CHANGELOG.md\");\""
Do you say to do this: `'php -r "if (file_exists(\"CHANGELOG.md\")) unlink(\"CHANGELOG.md\");"'` ?

But this generate an error, because the json file does not accept single quotes

2022-02-07 21:33 UTC, Ocramius commented on composer.json
> +            "php -r \"if (file_exists(\"CHANGELOG.md\")) unlink(\"CHANGELOG.md\");\""
No, I mean that `\"CHANGELOG.md\"` won't work, if you use double quotes. You will need single quotes or further escaping there.

2022-02-07 21:33 UTC, gildonei commented on composer.json
> +            "php -r \"if (file_exists(\"CHANGELOG.md\")) unlink(\"CHANGELOG.md\");\""
![image](https://user-images.githubusercontent.com/1370979/152875532-bb088657-34d4-4da1-92b0-ba88f368969c.png)

2022-02-07 21:43 UTC, gildonei commented on composer.json
> +            "php -r \"if (file_exists(\"CHANGELOG.md\")) unlink(\"CHANGELOG.md\");\""
> No, I mean that `\"CHANGELOG.md\"` won't work, if you use double quotes. You will need single quotes or further escaping there.

Done!

2022-02-07 21:47 UTC, gildonei reviewed
Could I also incluide a new line in .gitignore in this PR? (VSCode .history/*)

2022-02-08 09:54 UTC, froschdesign commented
@gildonei 
> Could I also incluide a new line in .gitignore in this PR? (VSCode .history/*)

There is no need to extend the `.gitignore` file of this repository, this can be done via a [global `.gitignore` file](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) or via an [exclude rule](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#excluding-local-files-without-creating-a-gitignore-file).

2022-02-08 09:55 UTC, froschdesign commented
It looks like this solution can also be added to laminas-mvc-skeleton: https://github.com/laminas/laminas-mvc-skeleton/issues/42

2022-02-08 11:46 UTC, gildonei reviewed
Updated modules.config.php from master
Updated composer.lock from master
Fixed composer.json _post-create-project-cmd_ for windows

Signed-off-by: Gildonei <gildonei.mendes@gmail.com>

2022-02-08 12:22 UTC, gildonei commented
I gave up
Signed-off-by: Gildonei M A Junior <gildonei.mendes@gmail.com>

2022-02-08 12:51 UTC, gildonei commented
Hello @Ocramius can you give a help how to pass those conflicts?

2022-02-08 12:54 UTC, gildonei reviewed
Signed-off-by: Gildonei M A Junior <gildonei.mendes@gmail.com>

2022-02-08 12:54 UTC, gildonei reviewed
Signed-off-by: Gildonei M A Junior <gildonei.mendes@gmail.com>

2022-02-08 12:54 UTC, gildonei reviewed
Signed-off-by: Gildonei M A Junior <gildonei.mendes@gmail.com>

2022-02-08 12:54 UTC, gildonei reviewed
Signed-off-by: Gildonei M A Junior <gildonei.mendes@gmail.com>

2022-02-08 17:08 UTC, closed without merging

2022-02-08 17:15 UTC, Ocramius commented
Was this supposed to be closed?

2022-02-08 17:53 UTC, gildonei commented
Yes I can't solve all issues in this PR, so, I create a new fork, and will
try from scratch again sending only composer.json file

Em ter., 8 de fev. de 2022 às 14:15, Marco Pivetta ***@***.***>
escreveu:

> Was this supposed to be closed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/laminas-api-tools/api-tools-skeleton/pull/48#issuecomment-1032861319>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKOWYZAFAMCQUPQAWQPAP3U2FFT5ANCNFSM5NYTVTNA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>